name: VulnEye Nightly
on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch: {}
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run VulnEye
        run: |
          python src/vulneye.py --inventory assets/sample_inventory.json --output examples/sample_report.html
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: vulneye-report
          path: examples/sample_report.html
